name: Node.js CI

# Trigger workflow on push or pull request to master/main
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test || echo "No tests found"

      # Step 5: Start application and check if running
      - name: Start application
        run: |
          npm start &
          sleep 10
          curl -f http://localhost:3000 || (echo "App did not start" && exit 1)

      # Step 6: Build Docker image (optional)
      - name: Build Docker image
        if: github.event_name == 'push' # optional: only build on push
        run: |
          docker build -t simple-nodejs-app:latest .

